config/routes.rb
Commlink::Application.routes.draw do

  get "players/upload"

  get "sessions/home"

  get "sessions/login"

  post "sessions/login_attempt"

  get "sessions/logout"

  post "sessions/logout"

  get "sessions/profile"

  get "sessions/settings"

  resources :skillsets

  resources :programsets

  resources :players

  resources :friends

  resources :npcs

  resources :nodes

  resources :groups

  resources :gamesessions

  resources :users

  resources :programset_templates

  resources :visiblenodes

  resources :node_templates

 

  

  root :to => "sessions#home"
end

app/models/node.rb
class Node < ActiveRecord::Base

  attr_accessible :desc, :firewall, :gamesession_id, :name, :pilot, :player_id, :programset_id, :response, :signal, :system

  belongs_to :player
  belongs_to :gamesession

  has_one :programset
  # has_one :user, through: :gamesession, foreign_key: :gm_id #Note, not always true.

  has_many :visiblenodes

  def item_names
    return { 
        system: "System", 
        firewall: "Firewall", 
        response: "Response", 
        signal: "Signal", 
        pilot: "Pilot"
    }
  end

  def create_from(params)
    programset = Programset.new
    if programset.create_from params
      self.programset_id = programset.id
    else
      return false
    end
    self.create(params)
    return self.save
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_filter :authenticate_user
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    if params[:player]
      @node = Nodes.find_by_player params[:player]
    else
      @node = Node.find(params[:id])
    end 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new
    respond_to do |format|
      if @node.create_from(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="Label"> name </div><br />
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <div class="Label"> desc </div><br />
    <%= text_field_tag :desc %>
  </div>
  <div class="field">
    <div class="Label"> firewall </div><br />
    <%= number_field_tag :firewall %>
  </div>
  <div class="field">
    <div class="Label"> system </div><br />
    <%= number_field_tag :system %>
  </div>
  <div class="field">
    <div class="Label"> pilot </div><br />
    <%= number_field_tag :pilot %>
  </div>
  <div class="field">
    <div class="Label"> signal </div><br />
    <%= number_field_tag :signal %>
  </div>
  <div class="field">
    <div class="Label"> response </div><br />
    <%= number_field_tag :response %>
  </div>
  <%= render 'programset/edit' %>
  <div class="actions">
    <%= submit_tag :Submit %>
  </div>

app/views/nodes/edit.html.erb
<div class="Title">Editing node</div>
<%= form_tag url_for(controller: 'nodes', action: 'update') do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<div class="Title">Listing nodes</div>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Firewall</th>
    <th>System</th>
    <th>Pilot</th>
    <th>Signal</th>
    <th>Response</th>
    <th>Programset</th>
    <th>Player</th>
    <th>Gamesession</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.name %></td>
    <td><%= node.desc %></td>
    <td><%= node.firewall %></td>
    <td><%= node.system %></td>
    <td><%= node.pilot %></td>
    <td><%= node.signal %></td>
    <td><%= node.response %></td>
    <td><%= link_to "Edit", edit_programset_path(node.programset_id) %></td>
    <% player = Player.find_by_id(node.player_id) %>
    <td><%= player ? player.name : "None"  %></td>
    <% game = Gamesessions.find_by_id(node.gamesession_id) %>
    <td><%= game ? game.name : "None" %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/list.html.erb
<div class="ListElement">
  <div class="Label">Name: <%= node.name %> <%= link_to "Edit", edit_node_path(node) %></div>
</div>

app/views/nodes/new.html.erb
<div class="Title">New node</div>
<%= form_tag url: {controller: 'nodes'} do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @node.desc %>
</p>

<p>
  <b>Firewall:</b>
  <%= @node.firewall %>
</p>

<p>
  <b>System:</b>
  <%= @node.system %>
</p>

<p>
  <b>Pilot:</b>
  <%= @node.pilot %>
</p>

<p>
  <b>Signal:</b>
  <%= @node.signal %>
</p>

<p>
  <b>Response:</b>
  <%= @node.response %>
</p>

<p>
  <b>Programset:</b>
  <%= link_to "Edit", edit_programset_path @node.programset_id %>
</p>

<p>
  <b>Player:</b>
  <%= Player.find_by_id(@node.player_id).name %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>