config/routes.rb
Commlink::Application.routes.draw do

  get "players/upload"

  get "sessions/home"

  get "sessions/login"

  post "sessions/login_attempt"

  get "sessions/logout"

  post "sessions/logout"

  get "sessions/profile"

  get "sessions/settings"

  resources :skillsets

  resources :programsets

  resources :players

  resources :friends

  resources :npcs

  resources :nodes

  resources :groups

  resources :gamesessions

  resources :users

  resources :programset_templates

  resources :visiblenodes

  resources :node_templates

 

  

  root :to => "sessions#home"
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :gamesession_id, :player_id

  belongs_to :player
  belongs_to :gamesession
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="Label"> gamesession_id </div><br />
    <%= number_field_tag :gamesession_id %>
  </div>
  <div class="field">
    <div class="Label"> player_id </div><br />
    <%= number_field_tag :player_id %>
  </div>
  <div class="actions">
    <%= submit_tag :Submit %>
  </div>

app/views/groups/edit.html.erb
<div class="Title">Editing group</div>
<%= form_tag url_for(controller: 'groups', action: 'update') do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="Title">Listing groups</div>

<div class="ListContainer">
  <% Gamesessions.all.each do |g| %>
    <div class="GroupContainer">
       <p><%= link_to "Group #{g.id}", edit_group_path(g) %><p>
        <% g.group.players.each do |p| %>
          <div class="ListElement">
            <%= link_to p.name, show_player_path(p) %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>



<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<div class="Title">New group</div>
<%= form_tag url: {controller: 'groups'} do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gamesession:</b>
  <%= @group.gamesession_id %>
</p>

<p>
  <b>Player:</b>
  <%= @group.player_id %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>