config/routes.rb
Commlink::Application.routes.draw do

  get "players/upload"

  get "sessions/home"

  get "sessions/login"

  post "sessions/login_attempt"

  get "sessions/logout"

  post "sessions/logout"

  get "sessions/profile"

  get "sessions/settings"

  resources :skillsets

  resources :programsets

  resources :players

  resources :friends

  resources :npcs

  resources :nodes

  resources :groups

  resources :gamesessions

  resources :users

  resources :programset_templates

  resources :visiblenodes

  resources :node_templates

 

  

  root :to => "sessions#home"
end

app/models/programset.rb
class Programset < ActiveRecord::Base
  attr_accessible :analyze, :armor, :attack, :biofeedback_filter, :black_hammer, :blackout, :command, :data_bomb, :decrypt, :defuse, :eccm, :edit, :encrypt, :exploit, :medic, :node_id, :reality_filter, :scan, :sniffer, :spoof, :stealth, :track

  belongs_to :node

  def update_from(params)
    self.analyze = params[:prog_analyze]
    self.armor = params[:prog_armor]
    self.attack = params[:prog_attack]
    self.biofeedback_filter = params[:prog_biofeedback_filter]
    self.black_hammer = params[:prog_black_hammer]
    self.blackout = params[:prog_blackout]
    self.browse = params[:prog_browse]
    self.command = params[:prog_command]
    self.data_bomb = params[:prog_data_bomb]
    self.decrypt = params[:prog_decrypt]
    self.defuse = params[:prog_defuse]
    self.eccm = params[:prog_eccm]
    self.edit = params[:prog_edit]
    self.encrypt = params[:prog_encrypt]
    self.exploit = params[:prog_exploit]
    self.medic = params[:prog_medic]
    self.node_id = @node.id
    self.reality_filter = params[:prog_reality_filter]
    self.scan = params[:prog_scan]
    self.sniffer = params[:prog_sniffer]
    self.spoof = params[:prog_spoof]
    self.stealth = params[:prog_stealth]
    self.track = params[:prog_track]
  end

  def zero
    self.analyze = 0
    self.armor = 0
    self.attack = 0
    self.biofeedback_filter = 0
    self.black_hammer = 0
    self.blackout = 0
    self.browse = 0
    self.command = 0
    self.data_bomb = 0
    self.decrypt = 0
    self.defuse = 0
    self.eccm = 0
    self.edit = 0
    self.encrypt = 0
    self.exploit = 0
    self.medic = 0
    self.reality_filter = 0
    self.scan = 0
    self.sniffer = 0
    self.spoof = 0
    self.stealth = 0
    self.track = 0
 end

 def item_names
        return { 
        analyze: "Analyze" , 
        armor: "Armor", 
        attack: "Attack", 
        biofeedback_filter: "Biofeedback", 
        black_hammer: "Black Hammer", 
        blackout: "Blackout", 
        browse: "Browse", 
        command: "Command", 
        data_bomb: "Data bomb", 
        decrypt: "Decrypt", 
        defuse: "Defuse", 
        eccm: "Eccm", 
        edit: "Edit", 
        encrypt: "Encrypt", 
        exploit: "Exploit", 
        medic: "Medic", 
        reality_filter: "Reality Filter", 
        scan: "Scan", 
        sniffer: "Sniffer", 
        spoof: "Spoof", 
        stealth: "Stealth", 
        track: "Track"
    }
  end

end

app/controllers/programsets_controller.rb
class ProgramsetsController < ApplicationController
  # GET /programsets
  # GET /programsets.json
  def index
    @programsets = Programset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programsets }
    end
  end

  # GET /programsets/1
  # GET /programsets/1.json
  def show
    @programset = Programset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programset }
    end
  end

  # GET /programsets/new
  # GET /programsets/new.json
  def new
    @programset = Programset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @programset }
    end
  end

  # GET /programsets/1/edit
  def edit
    @programset = Programset.find(params[:id])
  end

  # POST /programsets
  # POST /programsets.json
  def create
    @programset = Programset.new(params[:programset])
    
    respond_to do |format|
      if @programset.save
        format.html { redirect_to @programset, notice: 'Programset was successfully created.' }
        format.json { render json: @programset, status: :created, location: @programset }
      else
        format.html { render action: "new" }
        format.json { render json: @programset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programsets/1
  # PUT /programsets/1.json
  def update
    @programset = Programset.find(params[:id])

    respond_to do |format|
      if @programset.update_attributes(params[:programset])
        format.html { redirect_to @programset, notice: 'Programset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @programset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programsets/1
  # DELETE /programsets/1.json
  def destroy
    @programset = Programset.find(params[:id])
    @programset.destroy

    respond_to do |format|
      format.html { redirect_to programsets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programsets_helper.rb
module ProgramsetsHelper
end

app/views/programsets/_form.html.erb
  <% if @programset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programset.errors.count, "error") %> prohibited this programset from being saved:</h2>

      <ul>
      <% @programset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <div class="Label"> analyze </div><br />
    <%= number_field_tag :analyze %>
  </div>
  <div class="field">
    <div class="Label"> armor </div><br />
    <%= number_field_tag :armor %>
  </div>
  <div class="field">
    <div class="Label"> attack </div><br />
    <%= number_field_tag :attack %>
  </div>
  <div class="field">
    <div class="Label"> biofeedback_filter </div><br />
    <%= number_field_tag :biofeedback_filter %>
  </div>
  <div class="field">
    <div class="Label"> black_hammer </div><br />
    <%= number_field_tag :black_hammer %>
  </div>
  <div class="field">
    <div class="Label"> blackout </div><br />
    <%= number_field_tag :blackout %>
  </div>
  <div class="field">
    <div class="Label"> command </div><br />
    <%= number_field_tag :command %>
  </div>
  <div class="field">
    <div class="Label"> data_bomb </div><br />
    <%= number_field_tag :data_bomb %>
  </div>
  <div class="field">
    <div class="Label"> decrypt </div><br />
    <%= number_field_tag :decrypt %>
  </div>
  <div class="field">
    <div class="Label"> defuse </div><br />
    <%= number_field_tag :defuse %>
  </div>
  <div class="field">
    <div class="Label"> eccm </div><br />
    <%= number_field_tag :eccm %>
  </div>
  <div class="field">
    <div class="Label"> edit </div><br />
    <%= number_field_tag :edit %>
  </div>
  <div class="field">
    <div class="Label"> encrypt </div><br />
    <%= number_field_tag :encrypt %>
  </div>
  <div class="field">
    <div class="Label"> exploit </div><br />
    <%= number_field_tag :exploit %>
  </div>
  <div class="field">
    <div class="Label"> medic </div><br />
    <%= number_field_tag :medic %>
  </div>
  <div class="field">
    <div class="Label"> reality_filter </div><br />
    <%= number_field_tag :reality_filter %>
  </div>
  <div class="field">
    <div class="Label"> scan </div><br />
    <%= number_field_tag :scan %>
  </div>
  <div class="field">
    <div class="Label"> sniffer </div><br />
    <%= number_field_tag :sniffer %>
  </div>
  <div class="field">
    <div class="Label"> spoof </div><br />
    <%= number_field_tag :spoof %>
  </div>
  <div class="field">
    <div class="Label"> stealth </div><br />
    <%= number_field_tag :stealth %>
  </div>
  <div class="field">
    <div class="Label"> track </div><br />
    <%= number_field_tag :track %>
  </div>
  <div class="actions">
    <%= submit_tag :Submit %>
  </div>

app/views/programsets/edit.html.erb
<div class="Title">Editing programset</div>
<%= form_tag url_for(controller: 'programset', action: 'update') do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Show', @programset %> |
<%= link_to 'Back', programsets_path %>

app/views/programsets/index.html.erb
<div class="Title">Listing programsets</div>

<table>
  <tr>
    <th>Node</th>
    <th>Analyze</th>
    <th>Armor</th>
    <th>Attack</th>
    <th>Biofeedback filter</th>
    <th>Black hammer</th>
    <th>Blackout</th>
    <th>Command</th>
    <th>Data bomb</th>
    <th>Decrypt</th>
    <th>Defuse</th>
    <th>Eccm</th>
    <th>Edit</th>
    <th>Encrypt</th>
    <th>Exploit</th>
    <th>Medic</th>
    <th>Reality filter</th>
    <th>Scan</th>
    <th>Sniffer</th>
    <th>Spoof</th>
    <th>Stealth</th>
    <th>Track</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programsets.each do |programset| %>
  <tr>
    <td><%= link_to "Edit", edit_node_path(programset.node_id) %></td>
    <td><%= programset.analyze %></td>
    <td><%= programset.armor %></td>
    <td><%= programset.attack %></td>
    <td><%= programset.biofeedback_filter %></td>
    <td><%= programset.black_hammer %></td>
    <td><%= programset.blackout %></td>
    <td><%= programset.command %></td>
    <td><%= programset.data_bomb %></td>
    <td><%= programset.decrypt %></td>
    <td><%= programset.defuse %></td>
    <td><%= programset.eccm %></td>
    <td><%= programset.edit %></td>
    <td><%= programset.encrypt %></td>
    <td><%= programset.exploit %></td>
    <td><%= programset.medic %></td>
    <td><%= programset.reality_filter %></td>
    <td><%= programset.scan %></td>
    <td><%= programset.sniffer %></td>
    <td><%= programset.spoof %></td>
    <td><%= programset.stealth %></td>
    <td><%= programset.track %></td>
    <td><%= link_to 'Show', programset %></td>
    <td><%= link_to 'Edit', edit_programset_path(programset) %></td>
    <td><%= link_to 'Destroy', programset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Programset', new_programset_path %>

app/views/programsets/new.html.erb
<div class="Title">New programset</div>
<%= form_tag url: {controller: 'programsets'} do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Back', programsets_path %>

app/views/programsets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node:</b>
  <%= link_to "Show", show_node_path(@programset.node_id) %>
</p>

<p>
  <b>Analyze:</b>
  <%= @programset.analyze %>
</p>

<p>
  <b>Armor:</b>
  <%= @programset.armor %>
</p>

<p>
  <b>Attack:</b>
  <%= @programset.attack %>
</p>

<p>
  <b>Biofeedback filter:</b>
  <%= @programset.biofeedback_filter %>
</p>

<p>
  <b>Black hammer:</b>
  <%= @programset.black_hammer %>
</p>

<p>
  <b>Blackout:</b>
  <%= @programset.blackout %>
</p>

<p>
  <b>Command:</b>
  <%= @programset.command %>
</p>

<p>
  <b>Data bomb:</b>
  <%= @programset.data_bomb %>
</p>

<p>
  <b>Decrypt:</b>
  <%= @programset.decrypt %>
</p>

<p>
  <b>Defuse:</b>
  <%= @programset.defuse %>
</p>

<p>
  <b>Eccm:</b>
  <%= @programset.eccm %>
</p>

<p>
  <b>Edit:</b>
  <%= @programset.edit %>
</p>

<p>
  <b>Encrypt:</b>
  <%= @programset.encrypt %>
</p>

<p>
  <b>Exploit:</b>
  <%= @programset.exploit %>
</p>

<p>
  <b>Medic:</b>
  <%= @programset.medic %>
</p>

<p>
  <b>Reality filter:</b>
  <%= @programset.reality_filter %>
</p>

<p>
  <b>Scan:</b>
  <%= @programset.scan %>
</p>

<p>
  <b>Sniffer:</b>
  <%= @programset.sniffer %>
</p>

<p>
  <b>Spoof:</b>
  <%= @programset.spoof %>
</p>

<p>
  <b>Stealth:</b>
  <%= @programset.stealth %>
</p>

<p>
  <b>Track:</b>
  <%= @programset.track %>
</p>


<%= link_to 'Edit', edit_programset_path(@programset) %> |
<%= link_to 'Back', programsets_path %>