config/routes.rb
Commlink::Application.routes.draw do

  get "players/upload"

  get "sessions/home"

  get "sessions/login"

  post "sessions/login_attempt"

  get "sessions/logout"

  post "sessions/logout"

  get "sessions/profile"

  get "sessions/settings"

  resources :skillsets

  resources :programsets

  resources :players

  resources :friends

  resources :npcs

  resources :nodes

  resources :groups

  resources :gamesessions

  resources :users

  resources :programset_templates

  resources :visiblenodes

  resources :node_templates

 

  

  root :to => "sessions#home"
end

app/models/gamesession.rb
require 'csv'
class Gamesession < ActiveRecord::Base

  attr_accessible :gm_id, :name

  belongs_to :user

  has_many :groups
  has_many :players, through: :groups
  has_many :nodes, foreign_key: :gamesession_id


  validates :name, presence: true, length: { :in => 3..30 } 

  def update_from(params)
    self.name = params[:name]
    self.gm_id = session[:user_id]
  end

  def create_from(params)
    self.update_from(params)
    node_ids = CSV.parse(params[:nodelist_data])
    player_ids = CSV.parse(params[:playerlist_data])
    template_ids = CSV.parse(params[:nodetemplate_data])
    node_ids.each do |n|
      node = Node.find_by_id n
      node.gamesession_id = self.id
      node.save
    end
    player_ids.each do |p|
      player = Player.find_by_id p
      group = Group.new
      group.gamesession_id = self.id
      group.player_id = p
      group.save
    end
    template_ids.each do |n|
      node_temp = Node_template.find_by_id n
      node = node_template.instance_node
      node.gamesession_id = self.id
      node.gm_id = self.gm_id
      node.save
    end
  end
end

app/controllers/gamesessions_controller.rb
class GamesessionsController < ApplicationController
  before_filter :authenticate_user
  before_filter :authenticate_gm, only: [:edit, :delete, :update]
  before_filter :authenticate_gamesession, only: [:show ]
  
  def authenticate_gm
    if params[:id]
      session[:gamesession_id] = params[:id]
    end
    gamesession = Gamesession.find_by_id session[:gamesession_id]
    if !session[:gamesession_id]
      redirect_to controller: :gamesession, action: :index
      return false
    end
    if gamesession.gm_id == session[:user_id]
      return true
    else
      redirect_to controller: :gamesession, action: :edit
      return false
    end
  end

  def authenticate_gamesession
    if !session[:gamesession_id]
      redirect_to :index
      return false
    end
    if !session[:player_id]
      redirect_to controller: :player, action: :select
      return false
    end
    player = Player.find_by_id session[:player_id] 
    gamesession = Gamesession.find_by_id session[:gamesession_id]
    if gamesession.players.include? player  or @gamesession.gm_id == session[:user_id]
      return true
    else
      redirect_to :list
      return false
    end
  end

  # GET /gamesessions
  # GET /gamesessions.json
  def index
    @gamesessions = Gamesession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gamesessions }
    end
  end

  # GET /gamesessions/1
  # GET /gamesessions/1.json
  def show
    @gamesession = Gamesession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gamesession }
    end
  end

  # GET /gamesessions/new
  # GET /gamesessions/new.json
  def new
    @gamesession = Gamesession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gamesession }
    end
  end

  # GET /gamesessions/1/edit
  def edit
    @gamesession = Gamesession.find(params[:id])
  end

  # POST /gamesessions
  # POST /gamesessions.json
  def create
    @gamesession = Gamesession.new(params[:gamesession])

    respond_to do |format|
      if @gamesession.save
        format.html { redirect_to @gamesession, notice: 'Gamesession was successfully created.' }
        format.json { render json: @gamesession, status: :created, location: @gamesession }
      else
        format.html { render action: "new" }
        format.json { render json: @gamesession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gamesessions/1
  # PUT /gamesessions/1.json
  def update
    @gamesession = Gamesession.find(params[:id])

    respond_to do |format|
      if @gamesession.update_attributes(params[:gamesession])
        format.html { redirect_to @gamesession, notice: 'Gamesession was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gamesession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamesessions/1
  # DELETE /gamesessions/1.json
  def destroy
    @gamesession = Gamesession.find(params[:id])
    @gamesession.destroy

    respond_to do |format|
      format.html { redirect_to gamesessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gamesessions_helper.rb
module GamesessionsHelper
end

app/views/gamesessions/_form.html.erb
<div class="FormContainer">
  <%= javascript_tag "$(document).ready(function() {supress_edit(); supress_delete();});" %>
  <% if @gamesession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamesession.errors.count, "error") %> prohibited this gamesession from being saved:</h2>

      <ul>
      <% @gamesession.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="Label"> gm_id </div><br />
    <%= number_field_tag :gm_id %>
  </div>
  <div class="field">
    <div class="Label"> name </div><br />
    <%= text_field_tag :name %>
  </div>
  <%= render template: {layout: :switch}, locals: {left: {list: 'node/index' , id: 'nodesrc'}, right: {list: nil, id: 'nodelist'}  } %>
  <%= render template: {layout: :switch}, locals: {left: {list: 'nodetemplates/index' , id: 'nodetemplatesrc'}, right: {list: nil, id: 'notedemplatelist'}  } %>
  <%= render template: {layout: :switch}, locals: {left: {list: 'players/friends' , id: 'playersrc'}, right: {list: nil, id: 'playerlist'}  } %>
  <%= hidden_field_tag :nodelist_data %>
  <%= hidden_field_tag :playerlist_data %>
  <%= hidden_field_tag :nodetemplate_data %>
  <div class="actions">
    <%= submit_tag :Submit onclick: "parse_sel_submit('#gamesession', '.ListElement', {'#nodelist' : '#nodelist_data', '#playerlist' : '#playerlist_data', '#nodetemplate_data' : '#nodetemplatelist'});" %>
  </div>
</div>

app/views/gamesessions/edit.html.erb
<div class="Title">Editing gamesession</div>
<%= form_tag url_for(controller: 'gamesessions', action: 'update') do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Show', @gamesession %> |
<%= link_to 'Back', gamesessions_path %>

app/views/gamesessions/index.html.erb
<div class="Title">Playing</div>

<div class="ListContainer">
  <% @user.players.each do |p| %>
  <div class="ListElement">
    <b><%= p.name %></b>
  </div>
  <% p.gamesessions.each do |g| %>
    <div class= "ListElement">
      <%= link_to g.name, {:controller => :gamesession, :action => :play, :game_id => g.id, :player_id => p.id} %>
    </div>
  <% end %>
  <% end %>
</div>

<div class="Title">Running</div>
<div class="ListContainer">
  <% @user.gamesessions.each do |g| %>
  <div class= "ListElement"> 
    <%= link_to g.name, :action => :manage, :id => g.id %>
    <%= link_to image_tag("delete16.png", :border => 0), {:controller => :gamesession, :action => :delete, :id => g.id}, :class => "DeleteTag" %> 
  </div>
</div>
<br />

<%= button_to 'New', new_gamesession_path %>

app/views/gamesessions/new.html.erb
<div class="Title">New gamesession</div>
<%= form_tag url: {controller: 'gamesessions'} do %>
<%= render 'form' %>
<%= submit_tag :Submit %>
<% end %>
<%= link_to 'Back', gamesessions_path %>

app/views/gamesessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gm:</b>
  <%= Users.find_by_id(@gamesession.gm_id).username %>
</p>

<p>
  <b>Name:</b>
  <%= @gamesession.name %>
</p>
<div class="Title">Nodes</div>
<div class="ListContainer">
  <% @gamesession.nodes.each do |n| %>
    <div class="ListElement">
      <%= link_to n.name, edit_node_path(n) %>
    </div>
  <% end %>
</div>
<div class="Title">Players</div>
<div class="ListContainer">
  <% @gamesession.nodes.each do |p| %>
    <div class="ListElement">
      <%= link_to p.name, show_player_path(p) %>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_gamesession_path(@gamesession) %> |
<%= link_to 'Back', gamesessions_path %>